name: CI demo
on:
  push: 
    branches:
       [stage]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install Python
              uses: actions/setup-python@v1
              with:
                python-version: 3.10.14
            - name: Install dependencies
              run: make install
            - name: Linting
              run: make lint
            - name: Pytest
              run: make test
    load_test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v2
            - name: Install Python
              uses: actions/setup-python@v1
              with:
                python-version: 3.10.14
            - name: Install locust
              run: pip install locust
            - name: Run Load Test with Locust
              run: locust -f locustfile.py --headless -u 20 -r 5 --runtime 1m --host=https://localhost:5000/add?x=3&y=8 

                
