name: CI demo
on: [push]
jobs:
    build:
        runs-on: ububtu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install Python
              uses: actions/setup-python@v1
              with:
                python-version: 3.10
            - name: Install dependencies
              run: make install
            - name: Linting
              run: make lint
            - name: Pytest
              run: make test
                
